name: Deno

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deno
      uses: denoland/setup-deno@v1.1.3
      with:
        deno-version: "1.39.0"

    - uses: actions/checkout@v3

    - name: Build
      run: deno test --allow-read --allow-write --allow-env
